version: 0.2

env:
  variables:
    STACK_NAME: "application-stack"
    TEMPLATE_FILE: "application-cfn.yaml"
  parameter-store:
    AWS_REGION: "ca-central-1"
    VPC_ID: "vpc-0481a6fc3f330f41b"
    AMI_ID: "ami-0db18496905e01e3d"
    SUBNET_ID_1: "subnet-0f3429fb1a2c6603a"
    SUBNET_ID_2: "subnet-0e1b999d8178296a9"
    ASG_MIN_VALUE: "2"
    ASG_MAX_VALUE: "4"
        # PARAMETERS: |
        #             ParameterKey=VpcID,ParameterValue=vpc-0481a6fc3f330f41b
        #                           ParameterKey=AMIID,ParameterValue=ami-0db18496905e01e3d
        #             ParameterKey=SubnetID1,ParameterValue=subnet-0f3429fb1a2c6603a
        #             ParameterKey=SubnetID2,ParameterValue=subnet-0e1b999d8178296a9
        #             ParameterKey=ASGMinValue,ParameterValue=2
        #             ParameterKey=ASGMaxValue,ParameterValue=4
                

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade awscli

  pre_build:
    commands:
      - echo "Checking AWS CLI version..."
      - aws --version
      - echo "Validating CloudFormation template..."
      - aws cloudformation validate-template --template-body file://${TEMPLATE_FILE}

  build:
    commands:
      - echo "Deploying CloudFormation stack..."
      - aws cloudformation deploy \
          --template-file ${TEMPLATE_FILE} \
          --stack-name ${STACK_NAME} \
          --region $AWS_REGION \
          --capabilities CAPABILITY_NAMED_IAM \
          --parameter-overrides $(echo "${PARAMETERS}" | tr '\n' ' ')

  post_build:
    commands:
      - echo "Deployment complete!"
      - echo "Getting stack outputs..."
      - aws cloudformation describe-stacks --stack-name ${STACK_NAME} --query "Stacks[0].Outputs"